### ISSUE TITLE
https://github.com/OData/RESTier does not generate any code without any errors

### ISSUE THREAD

**Issue by kachalkov** [romfir/OpenApiLINQPadDriver#25]
[repo](https://github.com/OData/RESTier/tree/main/src/Microsoft.Restier.Samples.Northwind.AspNetCore)
no errors, generated swagger json looks ok to me, I tried with LinqPad 5 swagger driver and it was complaining about missing description somewhere...

**Comment by romfir** [comment]
Its a bug in `NSwag`, when first tag contains invalid characters (in your case `Categories.Category`) they will be pasted into client name resulting in inavlid C# code
I've reported it on their repo https://github.com/RicoSuter/NSwag/issues/4719
It only occurs when using `MultipleClientsFromFirstTagAndOperationNameGenerator`, for single client it seems to work as there is no name generated from this tag.

You did not get any errors? On my end it looks like this
<img width="182" alt="image" src="https://github.com/romfir/OpenApiLINQPadDriver/assets/33402460/1eba8780-ab77-4670-84ab-8e3fe09fbcf0">

**Comment by kachalkov** [comment]
Thank you for quick reply, I've updated to v0. 6 and now it shows errors as
well...

**Comment by kachalkov** [comment]
I did try single one and it works, but it takes quite a bit of time for our real db context:

36 seconds to compile for real size db, I assume because everything in one huge class...

**Comment by romfir** [comment]
Lets keep it open for now, I will probably end up implementing a fix for this on a driver side.

Would you be able to share swagger.json that was causing such long compilation times? Maybe I can look for a way to optimize driver generation :)
 Also do you have linqpad added in windows defender exclusions? There is a sample inside Linqpad that checks assembly loading times ([more here](https://forum.linqpad.net/discussion/3057/antivirus-performance-test))

**Comment by kachalkov** [comment]
Sorry, I'm not able to share our real one, but I assume if you use any 100
tables db context, you would see the slowness, but once again, I suspect it
is because it generates single class for everything...

**Comment by romfir** [comment]
totally understandable :) can you show me `Execution Times` explorer item while having `Debug Info` checked? Also could you run `Antivirus Performance Test` from LINQPad samples and post results here?
