### ISSUE TITLE
Timespan deserialize issue 

### ISSUE THREAD

**Issue by kachalkov** [romfir/OpenApiLINQPadDriver#34]
hi, there is seems to be an issue with Timespan being deserialized when calling swagger api endpoint, are there any way to configure deserialization to use Timespan converted or update to use System.Text.Json

**Comment by romfir** [comment]
Hello, you can choose what Json library to use in the settings
![image](https://github.com/romfir/OpenApiLINQPadDriver/assets/33402460/6a6727fa-2648-45c5-bc5f-b994946bbad1)
What library are you using to generate Open api document? If it is Swashbuckle it is possible that you are encountering this bug: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2505 where TimeSpan is generated as a normal class with all its properties: 
![image](https://github.com/romfir/OpenApiLINQPadDriver/assets/33402460/447dc6e4-68b5-4f17-91c1-1d9fcad679b4)

**Comment by kachalkov** [comment]
Thank you, that is very helpful!

**Comment by kachalkov** [comment]
Suppose to be fixed:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2804

**Comment by romfir** [comment]
You are correct, I've had some old version of Swashbucle. After updating to `6.6.2` it seems to be working
swagger json:
```yaml
"time": {
            "type": "string",
            "nullable": true,
            "example": "00:00:00"
          },
```

generated client:
```csharp
 [System.Text.Json.Serialization.JsonPropertyName("time")]
 public string Time { get; set; }
```

does it work for you as well?

**Comment by kachalkov** [comment]
Awesome!

**Comment by kachalkov** [comment]
we are using nswag.msbuild, but Swashbuckle.AspNetCore.Annotations update to 6.6.2 did the job, great driver, thank you!
