### ISSUE TITLE
ApiException  The HTTP status code of the response was not expected (401) From Behind Proxy

### ISSUE THREAD

**Issue by kachalkov** [romfir/OpenApiLINQPadDriver#7]
Hi, great driver,

just wondering if there is an option to allow proxy auth using windows auth?

**Comment by kachalkov** [comment]
https://github.com/seba76/SwaggerContextDriver/pull/3/files

        public virtual object[] GetContextConstructorArguments(IConnectionInfo cxInfo)
        {
            var httpClientHandler = new HttpClientHandler();
            var props = new ConnectionProperties(cxInfo);

            if (props.AuthOption == AuthenticationType.None)
                httpClientHandler.Credentials = null;
            else if (props.AuthOption == AuthenticationType.Basic)
                httpClientHandler.Credentials = new NetworkCredential(props.UserName, props.Password, props.Domain);
            else if (props.AuthOption == AuthenticationType.CurrentUser)
                httpClientHandler.Credentials = CredentialCache.DefaultNetworkCredentials;
            else
                throw new NotSupportedException("Authentication method specified in the Connection Dialog is not supported.");

            var httpClient = new HttpClient(httpClientHandler);
            return new[] { httpClient };
        }

**Comment by romfir** [comment]
Hi, thanks :)
do you need windows auth for authorizing requests to API or for downloading a swagger file?

The first one can be done by using `PrepareRequestFunction`, there is an example with bearer token in the [readme](https://github.com/romfir/OpenApiLINQPadDriver#preparerequestfunction)

Auth for downloading swagger/openapi files are not yet implemented, you could write a simple proxy (and run it for example in other linq file) or if you do not need the most recent swagger file you can simply download it to the disc and use it

**Comment by kachalkov** [comment]
Right, thank you, will have a look at the example :)

**Comment by kachalkov** [comment]
hi @romfir, I've tried the following, but without much succes:

PrepareRequestFunction = (httpClient, requestMessage, url) =>
{
	httpClient = new HttpClient(new HttpClientHandler
	{
		DefaultProxyCredentials = CredentialCache.DefaultNetworkCredentials
	});
};

**Comment by romfir** [comment]
It seems to be a problem with LINQPad iteslf, consider this code:
```csharp
var httpClient = new HttpClient(new HttpClientHandler
{
    Credentials = CredentialCache.DefaultNetworkCredentials,
});

var res = await httpClient.GetAsync("http://localhost:6001/weatherforecast3?numberOf=1&nothing=1");
```
where under localhost:6001 I have api with 
```csharp
builder.WebHost.UseHttpSys(options =>
		{
			options.Authentication.Schemes =
				AuthenticationSchemes.NTLM |
				AuthenticationSchemes.Negotiate;
			options.Authentication.AllowAnonymous = false;
		});
```

it works in Visual Studio (returns 200), but it does not in LINQPad, you probably should report it on https://forum.linqpad.net

**Comment by kachalkov** [comment]
Right, thank you, it could be proxy is the issue, but also apparently in
newer version of net it is not as straight forward:

https://github.com/dotnet/runtime/issues/24490

Including
@Joe Albahari ***@***.***> for any insights in NET7/8
